### ISSUE TITLE
Ignore Packages from stock SteamOS in an Update and Install

### ISSUE THREAD

**Issue by NightHammer1000** [steamdeck-linux/decker#13]
Packages that come Preinstalled in SteamOS should be ignored by Decker in an Update.
As of now, for example, Decker tries to update the Steam Decks Bootloader `steamos-efi` resulting in a OS Brick because the Boot Partitons are locked.

In my Opinion, everything from the `jupiter-beta` Repositiory should be ignored. Even when installing.
These kinds of Updates should only be done by the Steam Deck Update mechanism.

For Install, Best way to do this would be to check against a List of Packages and refusing to install if the Package is on the List of "System Packages"

**Comment by moxvallix** [comment]
Would you be able to make us such a list? As I don't have a deck right now, that would be really helpful.

We can just pass blacklisted packages to pacman to ignore when we run upgrade.
https://archlinux.org/pacman/pacman.8.html#_upgrade_options_apply_to_em_s_em_and_em_u_em_a_id_uo_a

**Comment by NightHammer1000** [comment]
This isnt actually a Issue anymore it seems.
Was probably a bad package at some point. Has been working since.
