### ISSUE TITLE
Install of Packages fail without unlocking the Filesystem

### ISSUE THREAD

**Issue by NightHammer1000** [steamdeck-linux/decker#8]
The SteamOS File system needs to be unlocked to install packages using decker

`error: cannot remove file '/usr/': Read-only file system`

decker should take care of that Automatically.
And it probably should relock itself after the installation again.

**Comment by moxvallix** [comment]
True. The original script did automatically disable read only, as well as properly configure pacman etc.
I have left that stuff out currently as I don't want it getting in the way when I am developing. I will add it back quickly though, before the next testing release.

**Comment by moxvallix** [comment]
@NightHammer1000 Can I get you to test that this stuff all works now in the latest release?
Preferably right after a system update.
